# doc: https://wiki.parity.io/Configuring-Parity-Ethereum.html#config-file

[parity]
chain = "chainspec.json"
base_path = "data"
auto_update = "none"

# name of your node
# Example: identity = "random_guy"
identity = "prototype93"

[network]
allow_ips = "public"
reserved_peers="bootnodes.txt"

[account]
password = [ "password.txt" ]

# address of your "mining key"
# Example: unlock = [ "0x8e1ca34f5718996f2531464f1323f959d8a8dd21" ]
unlock = [ "0x3f6a957c49d23353d949c342636eb8c54c216a78" ]

[mining]
usd_per_tx = "0"
min_gas_price = 1000000000
force_sealing = true
gas_floor_target = "8000000"
reseal_on_txs = "none"

# address of your "mining key"
# Example: engine_signer = "0x8e1ca34f5718996f2531464f1323f959d8a8dd21"
engine_signer = "0x3f6a957c49d23353d949c342636eb8c54c216a78"

[rpc]
disable = false
interface = "all"
apis = ["all"]

[websockets]
disable = false
interface = "all"
apis = ["all"]

[misc]
log_file = "parity.log"